/** @format */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import InfoNav from "@/components/CommonComponents/InfoNav";
import NavBar from "@/components/CommonComponents/NavBar";
import Footer from "@/components/CommonComponents/Footer";
import FooterBanner from "@/components/LandingPageComponents/FooterBanner";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gafbi Health Care",
  description: "Generated by Rahul Mallik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[var(--color-background)] font-sans">
        <ToastContainer />
        <InfoNav />
        <NavBar />

        {children}
        <FooterBanner />
        <Footer />
      </body>
    </html>
  );
}
